# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-28 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('roll_no', models.PositiveIntegerField()),
                ('age', models.PositiveIntegerField()),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='classes.Classes')),
            ],
        ),
    ]
